In [1]:
#Import Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

%matplotlib inline

In [3]:
df = pd.read_csv(r"C:\Users\bodak\Downloads\Churn_Modelling.csv")

In [4]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
X = df.iloc[:,3:-1]
Y = df.iloc[:,-1]

In [7]:
#Encoding

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [9]:
oe = OrdinalEncoder()

In [10]:
X.loc[:,'Geography':'Gender'] = oe.fit_transform(X.loc[:,'Geography':'Gender'])

In [11]:
X

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619        0.0     0.0   42       2       0.00              1   
1             608        2.0     0.0   41       1   83807.86              1   
2             502        0.0     0.0   42       8  159660.80              3   
3             699        0.0     0.0   39       1       0.00              2   
4             850        2.0     0.0   43       2  125510.82              1   
...           ...        ...     ...  ...     ...        ...            ...   
9995          771        0.0     1.0   39       5       0.00              2   
9996          516        0.0     1.0   35      10   57369.61              1   
9997          709        0.0     0.0   36       7       0.00              1   
9998          772        1.0     1.0   42       3   75075.31              2   
9999          792        0.0     0.0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [12]:
#Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
sc = StandardScaler()

In [15]:
X = sc.fit_transform(X)

In [16]:
X

array([[-0.32622142, -0.90188624, -1.09598752, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-0.44003595,  1.51506738, -1.09598752, ..., -1.54776799,
         0.97024255,  0.21653375],
       [-1.53679418, -0.90188624, -1.09598752, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.60498839, -0.90188624, -1.09598752, ..., -1.54776799,
         0.97024255, -1.00864308],
       [ 1.25683526,  0.30659057,  0.91241915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 1.46377078, -0.90188624, -1.09598752, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [17]:
#Splitting the data

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.25,random_state=1)

In [20]:
!pip install tensorflow

In [21]:
from tensorflow.keras import Sequential

In [22]:
from tensorflow.keras.layers import Dense

# 1)Initialize ANN

In [23]:
ann = Sequential()

In [24]:
ann

# 2)Add Hidden Layer

In [25]:
ann.add(Dense(units=6,activation='relu'))
ann.add(Dense(units=1,activation='sigmoid'))

ann.compile(optimizer='adam',loss = 'binary_crossentropy')

ann.fit(X_train,Y_train,batch_size=30,epochs=100)

ypred = ann.predict(X_test)

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5531
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4632
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4393
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4281
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4207
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4142
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4082
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4023
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3966
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3910
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3862
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3815
Epoch 13/100


250/250 [==============================] - 1s 2ms/step - loss: 0.3416
Epoch 100/100
79/79 [==============================] - 0s 2ms/step


In [26]:
ypred

array([[0.05297652],
       [0.10141549],
       [0.11962552],
       ...,
       [0.30748612],
       [0.48339134],
       [0.14986575]], dtype=float32)

In [27]:
ypred = ypred>0.5

In [28]:
ypred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [29]:
from sklearn.metrics import classification_report

In [30]:
print(classification_report(Y_test,ypred))

              precision    recall  f1-score   support

           0       0.88      0.97      0.92      1980
           1       0.79      0.50      0.61       520

    accuracy                           0.87      2500
   macro avg       0.84      0.73      0.77      2500
weighted avg       0.86      0.87      0.86      2500



# Regression Model

In [31]:
df = pd.read_csv('https://raw.githubusercontent.com/aishwaryamate/Datasets/main/cars.csv')

In [32]:
df.head()

symboling normalized-losses         make fuel-type   body-style  \
0          3                 ?  alfa-romero       gas  convertible   
1          3                 ?  alfa-romero       gas  convertible   
2          1                 ?  alfa-romero       gas    hatchback   
3          2               164         audi       gas        sedan   
4          2               164         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

  horsepower  city-mpg  highway-mpg  price  
0        111        21           27  13495  
1        111        21           27  16500  
2        154        19           26  16500  
3        102        24           30  13950  
4        115        18           22  17450

In [33]:
df.replace('?',np.nan,inplace=True)

In [34]:
df.head()

symboling normalized-losses         make fuel-type   body-style  \
0          3               NaN  alfa-romero       gas  convertible   
1          3               NaN  alfa-romero       gas  convertible   
2          1               NaN  alfa-romero       gas    hatchback   
3          2               164         audi       gas        sedan   
4          2               164         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

  horsepower  city-mpg  highway-mpg  price  
0        111        21           27  13495  
1        111        21           27  16500  
2        154        19           26  16500  
3        102        24           30  13950  
4        115        18           22  17450

In [35]:
from sklearn.impute import SimpleImputer

In [36]:
si = SimpleImputer()

df.iloc[:,[1,11]] = si.fit_transform(df.iloc[:,[1,11]])

df.head()

symboling  normalized-losses         make fuel-type   body-style  \
0          3              122.0  alfa-romero       gas  convertible   
1          3              122.0  alfa-romero       gas  convertible   
2          1              122.0  alfa-romero       gas    hatchback   
3          2              164.0         audi       gas        sedan   
4          2              164.0         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

   horsepower  city-mpg  highway-mpg  price  
0       111.0        21           27  13495  
1       111.0        21           27  16500  
2       154.0        19           26  16500  
3       102.0        24           30  13950  
4       115.0        18           22  17450

In [37]:
df.isna().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [38]:
cat_cols = df.select_dtypes(object).columns

In [39]:
from sklearn.preprocessing import OrdinalEncoder

In [40]:
oe = OrdinalEncoder()

In [41]:
df[cat_cols]=oe.fit_transform(df[cat_cols])

In [42]:
df.head()

symboling  normalized-losses  make  fuel-type  body-style  drive-wheels  \
0          3              122.0   0.0        1.0         0.0           2.0   
1          3              122.0   0.0        1.0         0.0           2.0   
2          1              122.0   0.0        1.0         2.0           2.0   
3          2              164.0   1.0        1.0         3.0           1.0   
4          2              164.0   1.0        1.0         3.0           0.0   

   engine-location  width  height  engine-type  engine-size  horsepower  \
0              0.0   64.1    48.8          0.0          130       111.0   
1              0.0   64.1    48.8          0.0          130       111.0   
2              0.0   65.5    52.4          5.0          152       154.0   
3              0.0   66.2    54.3          3.0          109       102.0   
4              0.0   66.4    54.3          3.0          136       115.0   

   city-mpg  highway-mpg  price  
0        21           27  13495  
1        21           27  16500  
2        19           26  16500  
3        24           30  13950  
4        18           22  17450

In [43]:
#feature scaling

In [44]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [45]:
X = sc.fit_transform(X)

In [46]:
X

array([[ 1.74347043,  0.        , -1.94825569, ...,  0.17106493,
        -0.64655303, -0.54605874],
       [ 1.74347043,  0.        , -1.94825569, ...,  0.17106493,
        -0.64655303, -0.54605874],
       [ 0.133509  ,  0.        , -1.94825569, ...,  1.26180693,
        -0.95301169, -0.69162706],
       ...,
       [-1.47645244, -0.85433189,  1.40664061, ...,  0.75448507,
        -1.10624102, -1.12833203],
       [-1.47645244, -0.85433189,  1.40664061, ...,  0.04423447,
         0.11959362, -0.54605874],
       [-1.47645244, -0.85433189,  1.40664061, ...,  0.24716321,
        -0.95301169, -0.83719538]])

In [47]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=1)

In [50]:
ann = Sequential()

ann.add(Dense(units=10,activation='relu'))
ann.add(Dense(units=1))

ann.compile(optimizer='adam',loss = 'mse')

ann.fit(X_train,Y_train,batch_size=32,epochs=250)

ypred = ann.predict(X_test)

Epoch 1/250
6/6 [==============================] - 1s 3ms/step - loss: 245652704.0000
Epoch 2/250
6/6 [==============================] - 0s 3ms/step - loss: 245650736.0000
Epoch 3/250
6/6 [==============================] - 0s 3ms/step - loss: 245648832.0000
Epoch 4/250
6/6 [==============================] - 0s 5ms/step - loss: 245647056.0000
Epoch 5/250
6/6 [==============================] - 0s 6ms/step - loss: 245645264.0000
Epoch 6/250
6/6 [==============================] - 0s 5ms/step - loss: 245643488.0000
Epoch 7/250
6/6 [==============================] - 0s 7ms/step - loss: 245641744.0000
Epoch 8/250
6/6 [==============================] - 0s 6ms/step - loss: 245639968.0000
Epoch 9/250
6/6 [==============================] - 0s 5ms/step - loss: 245638192.0000
Epoch 10/250
6/6 [==============================] - 0s 5ms/step - loss: 245636464.0000
Epoch 11/250
6/6 [==============================] - 0s 6ms/step - loss: 245634768.0000
Epoch 12/250
6/6 [==============================] - 

6/6 [==============================] - 0s 4ms/step - loss: 245188064.0000
Epoch 96/250
6/6 [==============================] - 0s 5ms/step - loss: 245176896.0000
Epoch 97/250
6/6 [==============================] - 0s 5ms/step - loss: 245165136.0000
Epoch 98/250
6/6 [==============================] - 0s 3ms/step - loss: 245154096.0000
Epoch 99/250
6/6 [==============================] - 0s 5ms/step - loss: 245143056.0000
Epoch 100/250
6/6 [==============================] - 0s 4ms/step - loss: 245132512.0000
Epoch 101/250
6/6 [==============================] - 0s 3ms/step - loss: 245122528.0000
Epoch 102/250
6/6 [==============================] - 0s 3ms/step - loss: 245112064.0000
Epoch 103/250
6/6 [==============================] - 0s 3ms/step - loss: 245100416.0000
Epoch 104/250
6/6 [==============================] - 0s 3ms/step - loss: 245088736.0000
Epoch 105/250
6/6 [==============================] - 0s 4ms/step - loss: 245076496.0000
Epoch 106/250
6/6 [==============================]

6/6 [==============================] - 0s 3ms/step - loss: 243689392.0000
Epoch 189/250
6/6 [==============================] - 0s 5ms/step - loss: 243668560.0000
Epoch 190/250
6/6 [==============================] - 0s 5ms/step - loss: 243646768.0000
Epoch 191/250
6/6 [==============================] - 0s 4ms/step - loss: 243624480.0000
Epoch 192/250
6/6 [==============================] - 0s 6ms/step - loss: 243602688.0000
Epoch 193/250
6/6 [==============================] - 0s 3ms/step - loss: 243578912.0000
Epoch 194/250
6/6 [==============================] - 0s 3ms/step - loss: 243556160.0000
Epoch 195/250
6/6 [==============================] - 0s 5ms/step - loss: 243533968.0000
Epoch 196/250
6/6 [==============================] - 0s 4ms/step - loss: 243510720.0000
Epoch 197/250
6/6 [==============================] - 0s 5ms/step - loss: 243488800.0000
Epoch 198/250
6/6 [==============================] - 0s 7ms/step - loss: 243467120.0000
Epoch 199/250
6/6 [===========================

In [52]:
from sklearn.metrics import r2_score,mean_squared_error

In [53]:
print(r2_score(Y_test,ypred))
print(mean_squared_error(Y_test,ypred))

-2.6604567017026324
200621250.62003133


In [54]:
ann.evaluate(X_train,Y_train)

6/6 [==============================] - 0s 5ms/step - loss: 242168160.0000


242168160.0